steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:latest'
  args: ['init']

- id: 'terraform plan'
  name: 'hashicorp/terraform:latest'
  args: ['plan']

- id: 'terraform apply'
  name: 'hashicorp/terraform:latest'
  args: ['apply', '-auto-approve']
